### ISSUE TITLE
Traceability agent YAML file seems to be the default

### ISSUE THREAD

**Issue by cwiechmann** [Axway/agents-mulesoft#14]
It looks like, that the Mulesoft Traceability Agent YAML-File is incorrect. It looks like the default from the SDK. 

https://github.com/Axway/agents-mulesoft/blob/main/mulesoft_traceability_agent/mulesoft_traceability_agent.yml

Can someone perhaps check?

**Comment by chrisccoy** [comment]
I did not notice this issue before, but the file shows mulesoft specific config.
