### ISSUE TITLE
Unable to view RAML API in Amplify Service Registry

### ISSUE THREAD

**Issue by mvenzke-axway** [Axway/agents-mulesoft#155]
**Describe the bug**

Unable to view RAML API created in Mulesoft in Amplify Service Registry

**To Reproduce**

1. Export an existing API running in the MuleSoft platform in RAML format
2. Create a new API based on that RAML API, importing that file as the backend API
3. Deploy

**Expected behavior**

API should be visible in Amplify Service Registry

**Logs**

```
{"apiAssetVersion":"1.0.0","apiID":18864163,"assetID":213012514,"assetName":"new-raml-api","level":"error","message":"error getting the service details: invalid character 'P' looking for beginning of value","time":"2023-07-31T08:12:41-07:00"}
```

**Version**
CentOS Linux release 7.9.2009
MuleSoft agent 1.1.23

**Additional context**

This has replicated in two different environments.

Apparently, the agent get API spec from MuleSoft and converts it from YAML to JSON. MuleSoft's GUI has different options for the "Download" actions for OAS and RAML APIs and appears to download to providing RAML.  We might have to call MuleSoft differently to get the desired API representation.

**Comment by cbordier** [comment]
@mvenzke-axway 
RAML format is not supported in Amplify platform
Supported types are:
OpenAPI 2.0 / OpenAPI 3.0 / AsyncAPI / Protobuf / WSDL / GraphQL.

**Comment by mvenzke-axway** [comment]
@cbordier Is there no way to get YAML from MuleSoft if it was created as YAML?  It looks like it has multiple export options from what Aleksandr showed me, we might just be requesting the default export instead of specifically the YAML export?

![image](https://github.com/Axway/agents-mulesoft/assets/60666497/7421bc94-d0fb-4951-8950-4248bf8eccf2)

**Comment by robertengaxway** [comment]
@mvenzke-axway We will investigate if RAML created APIs exported/discovered as YAML/OAS are part of a future feature enhancement.

**Comment by mvenzke-axway** [comment]
@robertengaxway I logged an idea at https://axway.aha.io/ideas/ideas/AMPAGE-I-17 a while ago.  Do we know when we might know more about our plans for this one?

**Comment by dgghinea** [comment]
Closing as RAML can now be discovered and parsed by the agent.
