### ISSUE TITLE
Request policies error

### ISSUE THREAD

**Issue by lmarchal88** [Axway/agents-mulesoft#183]
**Describe the bug**
When the discovery agent pull APIs there is an error on policies retreive

**Logs**
{"component":"httpClient","duration(ms)":488,"id":"d9c0d586-e902-44ea-ad2b-c5747bd27135","level":"trace","message":"request succeeded","method":"GET","package":"sdk.api","received(bytes)":15,"status":200,"time":"2023-11-15T15:30:17+01:00","url":"[https://anypoint.mulesoft.com/apimanager/api/v1/organizations/b4bce7ea-970a-4376-88e1-8c76f3723c67/environments/aafd1b9a-880f-4c68-a9ad-7986feb8fbee/apis/19111417/policies?masterOrganizationId=b4bce7ea-970a-4376-88e1-8c76f3723c67"}](https://anypoint.mulesoft.com/apimanager/api/v1/organizations/b4bce7ea-970a-4376-88e1-8c76f3723c67/environments/aafd1b9a-880f-4c68-a9ad-7986feb8fbee/apis/19111417/policies?masterOrganizationId=b4bce7ea-970a-4376-88e1-8c76f3723c67%22%7D)
{"apiAssetVersion":"1.0.0","apiID":19111417,"assetID":213106262,"assetName":"petstore-demo","level":"error","message":"error getting the service details: json: cannot unmarshal object into Go value of type []anypoint.Policy","time":"2023-11-15T15:30:17+01:00"}

** Here the result of the API Request on my mulesoft Environnement **
{
    "policies": []
}

**Comment by dgghinea** [comment]
Closing as this should not happen anymore in the latest agent version
